# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import cmath

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def solve(self):
        a = float(self.edit1.text())
        b = float(self.edit2.text())
        c = float(self.edit3.text())
        d = (b**2) - (4*a*c)
        root1 = (-b - cmath.sqrt(d)) / (2 * a)
        root2 = (-b + cmath.sqrt(d)) / (2 * a)
        print(root1)
        print(root2)
        root1=str(root1)
        root2=str(root2)
        self.ansx.setText(root1)
        self.ansy.setText(root2)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(436, 532)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 351, 61))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 361, 51))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 141, 51))
        self.label_3.setObjectName("label_3")
        self.edit1 = QtWidgets.QLineEdit(Form)
        self.edit1.setGeometry(QtCore.QRect(170, 170, 61, 51))
        self.edit1.setObjectName("edit1")
        self.edit3 = QtWidgets.QLineEdit(Form)
        self.edit3.setGeometry(QtCore.QRect(350, 170, 51, 51))
        self.edit3.setObjectName("edit3")
        self.edit2 = QtWidgets.QLineEdit(Form)
        self.edit2.setGeometry(QtCore.QRect(260, 170, 61, 51))
        self.edit2.setObjectName("edit2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 350, 58, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(17, 430, 91, 51))
        self.label_6.setObjectName("label_6")
        self.ansx = QtWidgets.QLineEdit(Form)
        self.ansx.setGeometry(QtCore.QRect(120, 350, 281, 51))
        self.ansx.setReadOnly(True)
        self.ansx.setObjectName("ansx")
        self.ansy = QtWidgets.QLineEdit(Form)
        self.ansy.setGeometry(QtCore.QRect(120, 430, 281, 51))
        self.ansy.setReadOnly(True)
        self.ansy.setObjectName("ansy")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(170, 260, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.solve)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Solving Quadratic equation"))
        self.label_2.setText(_translate("Form", "Such as ax^2+bx+c"))
        self.label_3.setText(_translate("Form", "please enter a,b and c"))
        self.label_5.setText(_translate("Form", "Root1="))
        self.label_6.setText(_translate("Form", "Root2="))
        self.pushButton.setText(_translate("Form", "Calculate"))
