# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'linequ.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LinEquation(object):
    def solve(self):
        try:
            a11 = float(self.a1.text())
            b11 = float(self.b1.text())
            c11 = float(self.c1.text())
            a22 = float(self.a2.text())
            b22 = float(self.b2.text())
            c22 = float(self.c2.text())
            a = np.array([[a11, b11],[a22,b22]])
            b = np.array([c11, c22])
            [x,y]=np.linalg.solve(a,b)
            print(x)
            print(y)
            x=str(x)
            y=str(y)
            self.ansx.setText(x)
            self.ansy.setText(y)
        except np.linalg.LinAlgError:
            print("Math Error :Unique solution not possible , enter valid input")
            self.ansx.setText("Math Error : Unique solution not possible")
            self.ansy.setText("Math Error : Unique solution not possible")

    def setupUi(self, LinEquation):
        LinEquation.setObjectName("LinEquation")
        LinEquation.resize(470, 630)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LinEquation.sizePolicy().hasHeightForWidth())
        LinEquation.setSizePolicy(sizePolicy)
        LinEquation.setMinimumSize(QtCore.QSize(470, 630))
        LinEquation.setMaximumSize(QtCore.QSize(470, 630))
        self.label = QtWidgets.QLabel(LinEquation)
        self.label.setGeometry(QtCore.QRect(40, 20, 351, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LinEquation)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 251, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(LinEquation)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 141, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(LinEquation)
        self.label_4.setGeometry(QtCore.QRect(10, 230, 121, 41))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.a1 = QtWidgets.QLineEdit(LinEquation)
        self.a1.setGeometry(QtCore.QRect(160, 160, 61, 41))
        self.a1.setObjectName("a1")
        self.b1 = QtWidgets.QLineEdit(LinEquation)
        self.b1.setGeometry(QtCore.QRect(250, 160, 61, 41))
        self.b1.setObjectName("b1")
        self.c1 = QtWidgets.QLineEdit(LinEquation)
        self.c1.setGeometry(QtCore.QRect(340, 160, 61, 41))
        self.c1.setObjectName("c1")
        self.a2 = QtWidgets.QLineEdit(LinEquation)
        self.a2.setGeometry(QtCore.QRect(160, 230, 61, 41))
        self.a2.setObjectName("a2")
        self.b2 = QtWidgets.QLineEdit(LinEquation)
        self.b2.setGeometry(QtCore.QRect(250, 230, 61, 41))
        self.b2.setObjectName("b2")
        self.c2 = QtWidgets.QLineEdit(LinEquation)
        self.c2.setGeometry(QtCore.QRect(340, 230, 61, 41))
        self.c2.setObjectName("c2")
        self.label_6 = QtWidgets.QLabel(LinEquation)
        self.label_6.setGeometry(QtCore.QRect(10, 370, 61, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(LinEquation)
        self.label_7.setGeometry(QtCore.QRect(10, 440, 71, 51))
        self.label_7.setObjectName("label_7")
        self.ansx = QtWidgets.QLineEdit(LinEquation)
        self.ansx.setGeometry(QtCore.QRect(100, 365, 301, 51))
        self.ansx.setReadOnly(True)
        self.ansx.setObjectName("ansx")
        self.ansy = QtWidgets.QLineEdit(LinEquation)
        self.ansy.setGeometry(QtCore.QRect(100, 440, 301, 51))
        self.ansy.setReadOnly(True)
        self.ansy.setObjectName("ansy")
        self.pushButton = QtWidgets.QPushButton(LinEquation)
        self.pushButton.setGeometry(QtCore.QRect(150, 310, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.solve)

        self.retranslateUi(LinEquation)
        QtCore.QMetaObject.connectSlotsByName(LinEquation)

    def retranslateUi(self, LinEquation):
        _translate = QtCore.QCoreApplication.translate
        LinEquation.setWindowTitle(_translate("LinEquation", "Form"))
        self.label.setText(_translate("LinEquation", "Solution Equation Group"))
        self.label_2.setText(_translate("LinEquation", "The form of the equation is as follows a1x + b1y = c1 and a2x + b2y = c2"))
        self.label_3.setText(_translate("LinEquation", "please enter a1, b1 and c1"))
        self.label_4.setText(_translate("LinEquation", "please enter a2, b2 and c2"))
        self.label_6.setText(_translate("LinEquation", "x  = "))
        self.label_7.setText(_translate("LinEquation", "y  = "))
        self.pushButton.setText(_translate("LinEquation", "Calculate"))
