# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from equation import Ui_Form
from linequ import Ui_LinEquation
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Menu(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindowl(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LinEquation()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(436, 532)
        self.label = QtWidgets.QLabel(Menu)
        self.label.setGeometry(QtCore.QRect(110, 70, 181, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.linequ = QtWidgets.QPushButton(Menu)
        self.linequ.setGeometry(QtCore.QRect(60, 180, 311, 61))
        self.linequ.setObjectName("linequ")
        self.quadequ = QtWidgets.QPushButton(Menu)
        self.quadequ.setGeometry(QtCore.QRect(60, 290, 311, 61))
        self.quadequ.setObjectName("quadequ")
        self.linequ.clicked.connect(self.openWindowl)
        self.quadequ.clicked.connect(self.openWindow)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Form"))
        self.label.setText(_translate("Menu", "Equation Menu"))
        self.linequ.setText(_translate("Menu", "Solve liner equation in two variable"))
        self.quadequ.setText(_translate("Menu", "Solve quadratic equation"))
